#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Ambi.Resource", IsApplication=true)]

namespace Ambi
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::Ambi.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::Ambi.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::Ambi.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int backgroundColor = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int lineColor = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int textColor = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int theme_devicedefault_background = 2131099651;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int commentBorder = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int downvote = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int header = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int placeholder = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int upvote = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
<<<<<<< HEAD
			// aapt resource value: 0x7f050008
			public const int contentFrame = 2131034120;
=======
			// aapt resource value: 0x7f080004
			public const int Product = 2131230724;
>>>>>>> refs/remotes/origin/Design/Interface-Branch
			
			// aapt resource value: 0x7f08000e
			public const int comment = 2131230734;
			
<<<<<<< HEAD
			// aapt resource value: 0x7f050002
			public const int productIdInput = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int productIdText = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int productNameInput = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int productNameText = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int productSubmit = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int textView1 = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int textView2 = 2131034115;
=======
			// aapt resource value: 0x7f080012
			public const int comment2 = 2131230738;
			
			// aapt resource value: 0x7f080010
			public const int commentSection = 2131230736;
			
			// aapt resource value: 0x7f08000d
			public const int commentSectionLayout = 2131230733;
			
			// aapt resource value: 0x7f080013
			public const int contentFrame = 2131230739;
			
			// aapt resource value: 0x7f08000c
			public const int downvoteImage = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int downvotes = 2131230731;
			
			// aapt resource value: 0x7f080002
			public const int head_image = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int headline = 2131230723;
			
			// aapt resource value: 0x7f080011
			public const int newCommentButton = 2131230737;
			
			// aapt resource value: 0x7f080005
			public const int productImage = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int productName = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int productPage = 2131230720;
			
			// aapt resource value: 0x7f080007
			public const int rating = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int ratingWrapper = 2131230728;
			
			// aapt resource value: 0x7f08000f
			public const int send = 2131230735;
			
			// aapt resource value: 0x7f080001
			public const int topBar = 2131230721;
			
			// aapt resource value: 0x7f08000a
			public const int upvoteImage = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int upvotes = 2131230729;
>>>>>>> refs/remotes/origin/Design/Interface-Branch
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int CommentPage = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
<<<<<<< HEAD
			// aapt resource value: 0x7f030001
			public const int NewProduct = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ProductPage = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int zxingscanneractivitylayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int zxingscannerfragmentlayout = 2130903044;
=======
			// aapt resource value: 0x7f040002
			public const int ProductPage = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int zxingscanneractivitylayout = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int zxingscannerfragmentlayout = 2130968580;
>>>>>>> refs/remotes/origin/Design/Interface-Branch
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Custom = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
